//! `frost-selftest`: on a LOCAL ZSA node only, issue an asset under a 2-of-3 FROST group key and
//! check what the node accepts and refuses. Keys are generated by DKG in memory and discarded.

use orchard::keys::{FullViewingKey, Scope, SpendingKey};
use rand::RngCore;
use rand::rngs::OsRng;

use crate::issue::{self, BuildOptions};
use crate::rpc::Node;
use crate::{frost, metadata, threshold};

fn throwaway_address() -> orchard::Address {
    loop {
        let mut b = [0u8; 32];
        OsRng.fill_bytes(&mut b);
        if let Some(sk) = Option::<SpendingKey>::from(SpendingKey::from_bytes(b)) {
            return FullViewingKey::from(&sk).address_at(0u32, Scope::External);
        }
    }
}

pub fn run(node_url: &str) -> Result<bool, String> {
    let local = ["http://127.0.0.1:", "http://localhost:", "http://[::1]:"];
    if !local.iter().any(|p| node_url.starts_with(p)) {
        return Err(format!("refusing {node_url}: frost-selftest only runs against a node on localhost"));
    }
    let node = Node::new(node_url);
    if node.block_count()? == 0 {
        issue::empty_block(node_url)?;
    }
    let mut all_ok = true;
    let mut report = |ok: bool, what: String| {
        all_ok &= ok;
        println!("{} {what}", if ok { "PASS" } else { "FAIL" });
    };

    // A 2-of-3 group by DKG, and a second, unrelated group.
    let (keys, pkp) = frost::dkg_in_process(3, 2)?;
    let (other_keys, other_pkp) = frost::dkg_in_process(3, 2)?;
    let xonly = frost::group_xonly(&pkp)?;
    let ik = threshold::issuer_from_xonly(&xonly)?;
    println!("group issuer key: {}", hex::encode(ik.encode()));
    let ids: Vec<_> = (1..=3).map(frost::identifier).collect::<Result<_, _>>()?;

    // A local test asset (Cachet v1 metadata, localnet cluster, made-up mint).
    let spec = metadata::CoinSpec {
        name: "Local threshold issuer test (no value)".into(),
        cluster: "localnet".into(),
        mint: metadata::base58_encode(&{
            let mut m = [0u8; 32];
            OsRng.fill_bytes(&mut m);
            m
        }),
        decimals: 6,
        note: "Local test. No value.".into(),
    };
    let bundle = spec.bundle().map_err(|p| p.join("; "))?;
    let envelope = metadata::envelope_for(&bundle)?;

    let attempt = |sig: Option<Vec<u8>>, label: &str| -> Result<(bool, String), String> {
        let u = threshold::build_unsigned(&ik, &envelope, 1000, throwaway_address(), &BuildOptions::default(), &node)?;
        let tx = match sig {
            Some(s) => threshold::attach(u.tx, &s)?,
            None => u.tx,
        };
        let txid = tx.txid().to_string();
        let local = threshold::verify_issuance_signature(&tx);
        let submitted = issue::submit(node_url, tx);
        Ok((submitted.is_ok(), format!(
            "{label}: tx {txid}; BIP-340 check here: {}; node: {}",
            if local.is_ok() { "valid" } else { "invalid" },
            match &submitted { Ok(h) => format!("accepted at height {h}"), Err(e) => format!("refused ({e})") }
        )))
    };
    let sighash_of = |ik: &orchard::issuance::auth::IssueValidatingKey<orchard::issuance::auth::ZSASchnorr>| -> Result<(threshold::Unsigned, Vec<u8>), String> {
        let u = threshold::build_unsigned(ik, &envelope, 1000, throwaway_address(), &BuildOptions::default(), &node)?;
        let s = u.sighash.to_vec();
        Ok((u, s))
    };

    // 1. The placeholder signature: refused.
    let (accepted, line) = attempt(None, "1. no real signature (placeholder)")?;
    report(!accepted, line);

    // 2. Signers 1 and 3 sign the sighash: accepted.
    let (u, msg) = sighash_of(&ik)?;
    let sig = frost::sign_in_process(&keys, &[ids[0], ids[2]], &pkp, &msg, false)?;
    let tx = threshold::attach(u.tx, &sig)?;
    let txid = tx.txid().to_string();
    let local = threshold::verify_issuance_signature(&tx);
    let submitted = issue::submit(node_url, tx);
    let accepted = submitted.is_ok();
    report(
        accepted && local.is_ok(),
        format!("2. signers 1 and 3 (2 of 3): tx {txid}; node: {}", match &submitted { Ok(h) => format!("accepted at height {h}"), Err(e) => format!("refused ({e})") }),
    );
    let asset_hex = hex::encode(u.asset.to_bytes());
    match node.asset_state(&asset_hex)? {
        Some(st) => report(st.amount == 1000, format!("   node asset record: supply {} (asset {asset_hex})", st.amount)),
        None => report(false, "   node asset record: none".into()),
    }

    // 3. A Taproot-tweaked FROST signature: refused.
    let (u, msg) = sighash_of(&ik)?;
    let tweaked = frost::sign_in_process(&keys, &[ids[0], ids[1]], &pkp, &msg, true)?;
    let tx = threshold::attach(u.tx, &tweaked)?;
    let r = issue::submit(node_url, tx);
    report(r.is_err(), format!("3. Taproot-tweaked signature (signers 1 and 2): node {}", if r.is_ok() { "ACCEPTED" } else { "refused" }));

    // 4. A valid 2-of-3 signature from another group: refused.
    let (u, msg) = sighash_of(&ik)?;
    let foreign = frost::sign_in_process(&other_keys, &[ids[1], ids[2]], &other_pkp, &msg, false)?;
    let tx = threshold::attach(u.tx, &foreign)?;
    let r = issue::submit(node_url, tx);
    report(r.is_err(), format!("4. 2-of-3 signature by another group: node {}", if r.is_ok() { "ACCEPTED" } else { "refused" }));

    // 5. One signer alone cannot produce a signature.
    let (_, msg) = sighash_of(&ik)?;
    let one = frost::sign_in_process(&keys, &[ids[1]], &pkp, &msg, false);
    report(one.is_err(), format!("5. one signer alone: {}", match one { Ok(_) => "PRODUCED A SIGNATURE".into(), Err(e) => format!("no signature ({e})") }));

    // The supply did not change after the refused attempts.
    match node.asset_state(&asset_hex)? {
        Some(st) => report(st.amount == 1000, format!("   node asset record after the refused attempts: supply {}", st.amount)),
        None => report(false, "   node asset record: none".into()),
    }
    println!("{}", if all_ok { "FROST SELFTEST: ALL PASS" } else { "FROST SELFTEST: FAILURES" });
    Ok(all_ok)
}
