//! Issuance under a threshold key: no party ever holds the issuance authorizing key `isk`.
//!
//! ZIP 227's `issueAuthSig` is a BIP-340 Schnorr signature over the transaction's sighash, verified
//! under the issuer's x-only key `ik`. FROST(secp256k1, SHA-256) with BIP-340 challenges (the Zcash
//! Foundation's `frost-secp256k1-tr`, used untweaked) produces exactly such signatures from a key
//! that was generated by distributed key generation and exists only as shares.
//!
//! The transaction builder signs an issuance with `isk` itself, so this module assembles the
//! issuance transaction from the same public parts the builder uses:
//! 1. an OrchardZSA bundle with one zero-value ZEC output (needed to derive the issued notes' rho),
//! 2. the issue bundle, for the group key `ik`,
//! 3. the optional burn citation (a transparent OP_RETURN output, no inputs),
//! then computes the sighash, proves and signs the Orchard bundle (binding signature), and leaves the
//! issuance signature as a placeholder. The signature is authorizing data: it is not part of the
//! txid or the sighash, so the aggregate FROST signature is attached afterwards without changing
//! anything else. With no transparent inputs, the sighash equals the txid digest, so every signer
//! can recompute what it signs from the transaction itself.

use orchard::builder::BundleType;
use orchard::issuance::auth::{IssueAuthSig, IssueValidatingKey, ZSASchnorr};
use orchard::issuance::sighash_kind::{BIP340IssueAuthSig, IssueSighashKind};
use orchard::issuance::{IssueBundle, IssueInfo, Signed};
use orchard::keys::{FullViewingKey, Scope, SpendingKey};
use orchard::note::{AssetBase, AssetId};
use orchard::flavor::OrchardZSA;
use orchard::value::NoteValue;
use orchard::{Address, Anchor};
use rand::rngs::OsRng;
use zcash_primitives::transaction::builder::DEFAULT_TX_EXPIRY_DELTA;
use zcash_primitives::transaction::sighash::{SignableInput, signature_hash};
use zcash_primitives::transaction::txid::TxIdDigester;
use zcash_primitives::transaction::{
    Authorized, OrchardBundle, Transaction, TransactionData, TxVersion, Unauthorized,
};
use zcash_protocol::consensus::{BlockHeight, BranchId, REGTEST_NETWORK};
use zcash_protocol::memo::MemoBytes;
use zcash_protocol::value::{ZatBalance, Zatoshis};
use zcash_transparent::builder::{TransparentBuilder, TransparentSigningSet};

use crate::issue::BuildOptions;
use crate::rpc::Node;

/// An issuance transaction complete except for its issuance signature.
pub struct Unsigned {
    pub tx: Transaction,
    pub sighash: [u8; 32],
    pub asset: AssetBase,
}

/// The issuer as it appears on chain (`[0x00] || ik`) for an x-only group key.
pub fn issuer_from_xonly(xonly: &[u8; 32]) -> Result<IssueValidatingKey<ZSASchnorr>, String> {
    let mut enc = vec![0u8];
    enc.extend_from_slice(xonly);
    IssueValidatingKey::decode(&enc).map_err(|_| "not a valid x-only public key".to_string())
}

fn issue_sig(sig64: &[u8]) -> Result<BIP340IssueAuthSig, String> {
    let mut enc = vec![0u8];
    enc.extend_from_slice(sig64);
    let sig = IssueAuthSig::<ZSASchnorr>::decode(&enc).map_err(|_| "not a 64-byte BIP-340 signature".to_string())?;
    Ok(BIP340IssueAuthSig::new(IssueSighashKind::AllEffecting, sig))
}

/// Build an issuance of `amount` units of the asset (`ik`, `asset_desc`) to `recipient`, signed
/// everywhere except the issuance signature (a placeholder).
pub fn build_unsigned(
    ik: &IssueValidatingKey<ZSASchnorr>,
    asset_desc: &str,
    amount: u64,
    recipient: Address,
    opts: &BuildOptions,
    node: &Node,
) -> Result<Unsigned, String> {
    if amount == 0 {
        return Err("amount must be above zero".into());
    }
    if let Some(c) = opts.citation {
        if c.amount != amount && !opts.allow_citation_mismatch {
            return Err(format!("citation amount {} differs from the amount {amount}", c.amount));
        }
    }
    let mut rng = OsRng;
    let desc_hash = crate::metadata::asset_desc_hash(asset_desc.as_bytes());
    let asset = AssetBase::custom(&AssetId::new_v0(ik, &desc_hash));
    let first = node.asset_state(&hex::encode(asset.to_bytes()))?.is_none();

    let tip = node.block_count()?;
    let anchor = Option::from(Anchor::from_bytes(node.orchard_root(tip)?)).ok_or("the node's Orchard root is not a valid anchor")?;
    let target = BlockHeight::from_u32(u32::try_from(tip + 1).map_err(|_| "height")?);
    let branch = BranchId::for_height(&REGTEST_NETWORK, target);
    let version = TxVersion::suggested_for_branch(branch);
    let expiry = target + DEFAULT_TX_EXPIRY_DELTA;

    // 1. OrchardZSA bundle: one zero-value ZEC output to a throwaway address.
    let throwaway = loop {
        let mut bytes = [0u8; 32];
        rand::RngCore::fill_bytes(&mut rng, &mut bytes);
        if let Some(sk) = Option::<SpendingKey>::from(SpendingKey::from_bytes(bytes)) {
            break FullViewingKey::from(&sk).address_at(0u32, Scope::External);
        }
    };
    let mut ob = orchard::builder::Builder::new(BundleType::DEFAULT_ZSA, anchor);
    ob.add_output(None, throwaway, NoteValue::ZERO, AssetBase::zatoshi(), MemoBytes::empty().into_bytes())
        .map_err(|e| format!("orchard output: {e:?}"))?;
    let (orchard_bundle, _) = ob
        .build::<ZatBalance, OrchardZSA>(&mut rng)
        .map_err(|e| format!("orchard bundle: {e:?}"))?
        .ok_or("empty orchard bundle")?;

    // 2. Issue bundle for the group key.
    let (mut ib, built_asset) = IssueBundle::new(
        ik.clone(),
        desc_hash,
        Some(IssueInfo { recipient, value: NoteValue::from_raw(amount) }),
        first,
        &mut rng,
    );
    if built_asset != asset {
        return Err("the issue bundle's asset differs from the computed asset".into());
    }
    if opts.finalize {
        ib.finalize_action(&desc_hash).map_err(|e| format!("finalize: {e:?}"))?;
    }
    let first_nf = *orchard_bundle.actions().first().nullifier();
    let ib = ib.update_rho(&first_nf, &mut rng);

    // 3. Optional burn citation: a transparent OP_RETURN output, no inputs.
    let transparent = match opts.citation {
        Some(c) => {
            let mut tb = TransparentBuilder::empty();
            tb.add_null_data_output(&c.encode()).map_err(|e| format!("citation output: {e:?}"))?;
            tb.build()
        }
        None => None,
    };

    // The sighash, from the unauthorized transaction.
    let unauthed: TransactionData<Unauthorized> = TransactionData::from_parts(
        version,
        branch,
        0,
        expiry,
        Zatoshis::ZERO,
        transparent.clone(),
        None,
        None,
        Some(OrchardBundle::OrchardZSA(orchard_bundle)),
        Some(ib),
    );
    let txid_parts = unauthed.digest(TxIdDigester);
    let sighash: [u8; 32] = *signature_hash(&unauthed, &SignableInput::Shielded, &txid_parts).as_ref();

    // Authorize everything but the issuance signature.
    let transparent = transparent
        .map(|b| b.apply_signatures(|_| sighash, &TransparentSigningSet::new()))
        .transpose()
        .map_err(|e| format!("transparent: {e:?}"))?;
    let (orchard_unauth, issue_awaiting) = (unauthed.orchard_bundle().cloned(), unauthed.issue_bundle().cloned());
    let orchard = match orchard_unauth {
        Some(OrchardBundle::OrchardZSA(b)) => b
            .create_proof(&orchard::circuit::ProvingKey::build::<OrchardZSA>(), &mut rng)
            .and_then(|b| b.apply_signatures(&mut rng, sighash, &[]))
            .map_err(|e| format!("orchard proof/signatures: {e:?}"))?,
        _ => return Err("expected an OrchardZSA bundle".into()),
    };
    let placeholder = issue_sig(&[0u8; 64])?;
    let issue = issue_awaiting
        .ok_or("no issue bundle")?
        .prepare(sighash)
        .map_authorization(|_| Signed::new(placeholder));

    let authed: TransactionData<Authorized> = TransactionData::from_parts(
        version,
        branch,
        0,
        expiry,
        Zatoshis::ZERO,
        transparent,
        None,
        None,
        Some(OrchardBundle::OrchardZSA(orchard)),
        Some(issue),
    );
    let tx = authed.freeze().map_err(|e| format!("freeze: {e}"))?;
    if *tx.txid().as_ref() != sighash {
        return Err("the sighash is not the txid digest (transparent inputs?)".into());
    }
    Ok(Unsigned { tx, sighash, asset })
}

/// Put a 64-byte BIP-340 signature into a transaction's issue bundle. The txid does not change.
pub fn attach(tx: Transaction, sig64: &[u8]) -> Result<Transaction, String> {
    let sig = issue_sig(sig64)?;
    let d = tx.into_data();
    let issue = d
        .issue_bundle()
        .cloned()
        .ok_or("no issue bundle")?
        .map_authorization(|_| Signed::new(sig));
    let data: TransactionData<Authorized> = TransactionData::from_parts(
        d.version(),
        d.consensus_branch_id(),
        d.lock_time(),
        d.expiry_height(),
        d.zip233_amount(),
        d.transparent_bundle().cloned(),
        d.sprout_bundle().cloned(),
        d.sapling_bundle().cloned(),
        d.orchard_bundle().cloned(),
        Some(issue),
    );
    data.freeze().map_err(|e| format!("freeze: {e}"))
}

/// Check a transaction's issuance signature the way nodes do (BIP-340 over the txid digest).
pub fn verify_issuance_signature(tx: &Transaction) -> Result<(), String> {
    let b = tx.issue_bundle().ok_or("no issue bundle")?;
    b.ik()
        .verify(tx.txid().as_ref(), b.authorization().signature().sig())
        .map_err(|_| "the issuance signature does not verify under the issuer key".to_string())
}
